"""
Airtable field schemas for table creation via the Metadata API.
The first field in each list becomes the primary field (the "Name" column).
Requires token scope: schema.bases:write
"""

USERS_FIELDS: list[dict] = [
    {"name": "id", "type": "singleLineText"},
    {"name": "first_name", "type": "singleLineText"},
    {"name": "last_name", "type": "singleLineText"},
    {"name": "login", "type": "singleLineText"},
    {"name": "email", "type": "email"},
    {"name": "role", "type": "singleLineText"},
    {
        "name": "is_active",
        "type": "checkbox",
        "options": {"color": "greenBright", "icon": "check"},
    },
]

CLEAR_CUT_REPORTS_FIELDS: list[dict] = [
    {"name": "rapport_id", "type": "singleLineText"},
    {"name": "statut", "type": "singleLineText"},
    {"name": "date_signalement", "type": "singleLineText"},
    {"name": "debut_coupe", "type": "singleLineText"},
    {"name": "fin_coupe", "type": "singleLineText"},
    {"name": "surface_totale_ha", "type": "number", "options": {"precision": 4}},
    {"name": "surface_pente_ha", "type": "number", "options": {"precision": 4}},
    {
        "name": "surface_zone_ecologique_ha",
        "type": "number",
        "options": {"precision": 4},
    },
    {"name": "surface_feuillu_ha", "type": "number", "options": {"precision": 4}},
    {"name": "surface_resineux_ha", "type": "number", "options": {"precision": 4}},
    {"name": "surface_mixte_ha", "type": "number", "options": {"precision": 4}},
    {"name": "surface_peuplier_ha", "type": "number", "options": {"precision": 4}},
    {"name": "commune", "type": "singleLineText"},
    {"name": "code_postal", "type": "singleLineText"},
    {"name": "departement", "type": "singleLineText"},
    {"name": "code_departement", "type": "singleLineText"},
    {"name": "latitude", "type": "number", "options": {"precision": 6}},
    {"name": "longitude", "type": "number", "options": {"precision": 6}},
    {"name": "benevole_assigne", "type": "singleLineText"},
    {"name": "email_benevole", "type": "email"},
    {"name": "noms_zones_ecologiques", "type": "multilineText"},
    {
        "name": "dans_natura2000",
        "type": "checkbox",
        "options": {"color": "greenBright", "icon": "check"},
    },
    {"name": "nom_natura2000", "type": "multilineText"},
    {"name": "nb_versions", "type": "number", "options": {"precision": 0}},
    {"name": "regles_declenchees", "type": "singleLineText"},
    {"name": "benevole_terrain", "type": "singleLineText"},
    {"name": "email_benevole_terrain", "type": "email"},
    {"name": "date_inspection", "type": "singleLineText"},
    {"name": "meteo", "type": "singleLineText"},
    {"name": "type_peuplement_avant_coupe", "type": "singleLineText"},
    {
        "name": "presence_plantation",
        "type": "checkbox",
        "options": {"color": "greenBright", "icon": "check"},
    },
    {"name": "essence_plantee", "type": "singleLineText"},
    {"name": "photos_plantation", "type": "multilineText"},
    {
        "name": "panneau_chantier_visible",
        "type": "checkbox",
        "options": {"color": "greenBright", "icon": "check"},
    },
    {"name": "photos_panneau", "type": "multilineText"},
    {"name": "traversees_cours_eau", "type": "singleLineText"},
    {"name": "indices_destruction", "type": "singleLineText"},
    {"name": "etat_des_sols", "type": "singleLineText"},
    {"name": "photos_coupe", "type": "multilineText"},
    {"name": "photos_bois_coupes", "type": "multilineText"},
    {"name": "photos_etat_sols", "type": "multilineText"},
    {"name": "photos_chemins_acces", "type": "multilineText"},
    {
        "name": "coupe_dans_autre_zone_eco",
        "type": "checkbox",
        "options": {"color": "greenBright", "icon": "check"},
    },
    {"name": "type_autre_zone_eco", "type": "singleLineText"},
    {
        "name": "zone_eco_proximite",
        "type": "checkbox",
        "options": {"color": "greenBright", "icon": "check"},
    },
    {"name": "type_zone_eco_proximite", "type": "singleLineText"},
    {"name": "especes_protegees", "type": "multilineText"},
    {"name": "habitats_proteges", "type": "multilineText"},
    {
        "name": "demande_ddt",
        "type": "checkbox",
        "options": {"color": "greenBright", "icon": "check"},
    },
    {"name": "par_qui_ddt", "type": "singleLineText"},
    {"name": "entreprise_travaux", "type": "singleLineText"},
    {"name": "sous_traitant", "type": "singleLineText"},
    {"name": "proprietaire", "type": "singleLineText"},
    {
        "name": "certifie_pefc_fsc",
        "type": "checkbox",
        "options": {"color": "greenBright", "icon": "check"},
    },
    {
        "name": "propriete_plus_20ha",
        "type": "checkbox",
        "options": {"color": "greenBright", "icon": "check"},
    },
    {
        "name": "parcelle_soumise_psg",
        "type": "checkbox",
        "options": {"color": "greenBright", "icon": "check"},
    },
    {"name": "informations_complementaires", "type": "multilineText"},
    {
        "name": "pertinent_plainte_pefc",
        "type": "checkbox",
        "options": {"color": "greenBright", "icon": "check"},
    },
    {
        "name": "pertinent_plainte_rediii",
        "type": "checkbox",
        "options": {"color": "greenBright", "icon": "check"},
    },
    {
        "name": "pertinent_plainte_ofb",
        "type": "checkbox",
        "options": {"color": "greenBright", "icon": "check"},
    },
    {
        "name": "pertinent_alerte_cnpf_srgs",
        "type": "checkbox",
        "options": {"color": "greenBright", "icon": "check"},
    },
    {
        "name": "pertinent_alerte_cnpf_psg",
        "type": "checkbox",
        "options": {"color": "greenBright", "icon": "check"},
    },
    {
        "name": "pertinent_demande_psg",
        "type": "checkbox",
        "options": {"color": "greenBright", "icon": "check"},
    },
    {
        "name": "demande_engagee",
        "type": "checkbox",
        "options": {"color": "greenBright", "icon": "check"},
    },
]
