sequenceDiagram
    participant DataEng
    participant DataEngDB
    participant Backend

    DataEng->>DataEngDB: Insert new polygons
    activate DataEngDB
    DataEngDB-->>DataEng: Confirm insertion
    deactivate DataEngDB

    DataEng->>Backend: POST /clearcuts with polygon
    activate Backend
    Backend-->>DataEng: Return stored clearcut
    deactivate Backend
