"""migration

Revision ID: 07204d7b80f9
Revises: ca2056783232
Create Date: 2025-05-07 06:08:57.588133

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import geoalchemy2
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "07204d7b80f9"
down_revision: Union[str, None] = "ca2056783232"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "clear_cut_report_forms", "report_updated_at", new_column_name="created_at"
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "clear_cut_report_forms", "created_at", new_column_name="report_updated_at"
    )

    # ### end Alembic commands ###
