"""migration

Revision ID: 0f0afca3fb37
Revises: 01ce59715a3d
Create Date: 2025-04-17 10:22:39.789336

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "0f0afca3fb37"
down_revision: Union[str, None] = "01ce59715a3d"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "clear_cut_report_forms",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("report_id", sa.Integer(), nullable=False),
        sa.Column("editor_id", sa.Integer(), nullable=True),
        sa.Column("report_updated_at", sa.DateTime(), nullable=True),
        sa.Column("inspection_date", sa.DateTime(), nullable=True),
        sa.Column("weather", sa.String(), nullable=True),
        sa.Column("forest_description", sa.String(), nullable=True),
        sa.Column("remainingTrees", sa.Boolean(), nullable=True),
        sa.Column("species", sa.String(), nullable=True),
        sa.Column("workSignVisible", sa.Boolean(), nullable=True),
        sa.Column("waterzone_description", sa.String(), nullable=True),
        sa.Column("protected_zone_description", sa.String(), nullable=True),
        sa.Column("soil_state", sa.String(), nullable=True),
        sa.Column("ecological_zone", sa.Boolean(), nullable=True),
        sa.Column("ecological_zone_type", sa.String(), nullable=True),
        sa.Column("nearby_zone", sa.String(), nullable=True),
        sa.Column("nearby_zone_type", sa.String(), nullable=True),
        sa.Column("protected_species", sa.String(), nullable=True),
        sa.Column("protected_habitats", sa.String(), nullable=True),
        sa.Column("ddt_request", sa.Boolean(), nullable=True),
        sa.Column("ddt_request_owner", sa.String(), nullable=True),
        sa.Column("compagny", sa.String(), nullable=True),
        sa.Column("subcontractor", sa.String(), nullable=True),
        sa.Column("landlord", sa.String(), nullable=True),
        sa.Column("pefc_fsc_certified", sa.Boolean(), nullable=True),
        sa.Column("over_20_ha", sa.Boolean(), nullable=True),
        sa.Column("psg_required_plot", sa.Boolean(), nullable=True),
        sa.Column("relevant_for_pefc_complaint", sa.Boolean(), nullable=True),
        sa.Column("relevant_for_rediii_complaint", sa.Boolean(), nullable=True),
        sa.Column("relevant_for_ofb_complaint", sa.Boolean(), nullable=True),
        sa.Column("relevant_for_alert_cnpf_ddt_srgs", sa.Boolean(), nullable=True),
        sa.Column("relevant_for_alert_cnpf_ddt_psg_thresholds", sa.Boolean(), nullable=True),
        sa.Column("relevant_for_psg_request", sa.Boolean(), nullable=True),
        sa.Column("request_engaged", sa.String(), nullable=True),
        sa.Column("other", sa.String(), nullable=True),
        sa.ForeignKeyConstraint(
            ["report_id"],
            ["clear_cuts_reports.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_clear_cut_report_forms_editor_id"),
        "clear_cut_report_forms",
        ["editor_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_clear_cut_report_forms_forest_description"),
        "clear_cut_report_forms",
        ["forest_description"],
        unique=False,
    )
    op.create_index(
        op.f("ix_clear_cut_report_forms_id"), "clear_cut_report_forms", ["id"], unique=False
    )
    op.create_index(
        op.f("ix_clear_cut_report_forms_species"),
        "clear_cut_report_forms",
        ["species"],
        unique=False,
    )
    op.create_index(
        op.f("ix_clear_cut_report_forms_weather"),
        "clear_cut_report_forms",
        ["weather"],
        unique=False,
    )
    op.alter_column(
        "clear_cuts_reports",
        "slope_area_ratio_percentage",
        existing_type=sa.DOUBLE_PRECISION(precision=53),
        nullable=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "clear_cuts_reports",
        "slope_area_ratio_percentage",
        existing_type=sa.DOUBLE_PRECISION(precision=53),
        nullable=True,
    )
    op.drop_index(
        op.f("ix_clear_cut_report_forms_weather"), table_name="clear_cut_report_forms"
    )
    op.drop_index(
        op.f("ix_clear_cut_report_forms_species"), table_name="clear_cut_report_forms"
    )
    op.drop_index(op.f("ix_clear_cut_report_forms_id"), table_name="clear_cut_report_forms")
    op.drop_index(
        op.f("ix_clear_cut_report_forms_forest_description"),
        table_name="clear_cut_report_forms",
    )
    op.drop_index(
        op.f("ix_clear_cut_report_forms_editor_id"), table_name="clear_cut_report_forms"
    )
    op.drop_table("clear_cut_report_forms")
    # ### end Alembic commands ###
