"""Added index on 'clear_cuts.report_id'

Revision ID: 19e644f11e20
Revises: 9a447236a041
Create Date: 2025-12-17 07:47:33.996564

"""

from collections.abc import Sequence

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "19e644f11e20"
down_revision: str | None = "9a447236a041"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(
        op.f("ix_clear_cuts_report_id"), "clear_cuts", ["report_id"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_clear_cuts_report_id"), table_name="clear_cuts")
    # ### end Alembic commands ###
