"""migration

Revision ID: 223aeb833685
Revises: b5935c34f9bd
Create Date: 2025-03-23 13:39:45.498231

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "223aeb833685"
down_revision: Union[str, None] = "b5935c34f9bd"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("clear_cuts", sa.Column("address", sa.String(), nullable=False))
    op.add_column("clear_cuts", sa.Column("name_natura", sa.String(), nullable=True))
    op.add_column("clear_cuts", sa.Column("number_natura", sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("clear_cuts", "number_natura")
    op.drop_column("clear_cuts", "name_natura")
    op.drop_column("clear_cuts", "address")
    # ### end Alembic commands ###
