"""migration

Revision ID: 342bfc046428
Revises: 9ba44a77af28
Create Date: 2025-03-23 14:32:59.509245

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "342bfc046428"
down_revision: Union[str, None] = "9ba44a77af28"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("users", sa.Column("password", sa.String(), nullable=True))
    op.create_index(op.f("ix_users_password"), "users", ["password"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_users_password"), table_name="users")
    op.drop_column("users", "password")
    # ### end Alembic commands ###
