"""migration

Revision ID: 41e62d8226ee
Revises: 73a55cff34d1
Create Date: 2025-03-26 07:21:51.176193

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import geoalchemy2


# revision identifiers, used by Alembic.
revision: str = '41e62d8226ee'
down_revision: Union[str, None] = '73a55cff34d1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('clear_cuts', sa.Column('city_id', sa.Integer(), nullable=True))
    op.drop_index('ix_clear_cuts_department_id', table_name='clear_cuts')
    op.create_index(op.f('ix_clear_cuts_city_id'), 'clear_cuts', ['city_id'], unique=False)
    op.drop_constraint('clear_cuts_department_id_fkey', 'clear_cuts', type_='foreignkey')
    op.create_foreign_key(None, 'clear_cuts', 'cities', ['city_id'], ['id'])
    op.drop_column('clear_cuts', 'department_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('clear_cuts', sa.Column('department_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'clear_cuts', type_='foreignkey')
    op.create_foreign_key('clear_cuts_department_id_fkey', 'clear_cuts', 'departments', ['department_id'], ['id'])
    op.drop_index(op.f('ix_clear_cuts_city_id'), table_name='clear_cuts')
    op.create_index('ix_clear_cuts_department_id', 'clear_cuts', ['department_id'], unique=False)
    op.drop_column('clear_cuts', 'city_id')
    # ### end Alembic commands ###
