"""Add assignment_requested_by_id

Revision ID: 548e40e6ac01
Revises: 7aa82f4156e0
Create Date: 2026-04-30 08:51:45.542332

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "548e40e6ac01"
down_revision: str | None = "7aa82f4156e0"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "clear_cuts_reports",
        sa.Column("assignment_requested_by_id", sa.Integer(), nullable=True),
    )
    op.create_foreign_key(
        None, "clear_cuts_reports", "users", ["assignment_requested_by_id"], ["id"]
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "clear_cuts_reports", type_="foreignkey")
    op.drop_column("clear_cuts_reports", "assignment_requested_by_id")
    # ### end Alembic commands ###
