"""migration

Revision ID: 5ccd539dde75
Revises: 7da0b1b74155
Create Date: 2025-07-31 20:33:50.205009

"""

from collections.abc import Sequence

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "5ccd539dde75"
down_revision: str | None = "7da0b1b74155"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "clear_cut_report_forms", sa.Column("planting_images", sa.JSON(), nullable=True)
    )
    op.drop_column("clear_cut_report_forms", "images_plantation")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "clear_cut_report_forms",
        sa.Column(
            "images_plantation",
            postgresql.JSON(astext_type=sa.Text()),
            autoincrement=False,
            nullable=True,
        ),
    )
    op.drop_column("clear_cut_report_forms", "planting_images")
    # ### end Alembic commands ###
