"""migration

Revision ID: 628340fc4cec
Revises: 223aeb833685
Create Date: 2025-03-24 09:09:35.351860

"""

from typing import Sequence, Union

from alembic import op
import geoalchemy2


# revision identifiers, used by Alembic.
revision: str = "628340fc4cec"
down_revision: Union[str, None] = "223aeb833685"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "clear_cuts",
        "location",
        existing_type=geoalchemy2.types.Geometry(
            geometry_type="POINT",
            from_text="ST_GeomFromEWKT",
            name="geometry",
            _spatial_index_reflected=True,
        ),
        type_=geoalchemy2.types.Geometry(
            geometry_type="POINT", srid=4326, from_text="ST_GeomFromEWKT", name="geometry"
        ),
        existing_nullable=True,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "clear_cuts",
        "location",
        existing_type=geoalchemy2.types.Geometry(
            geometry_type="POINT", srid=4326, from_text="ST_GeomFromEWKT", name="geometry"
        ),
        type_=geoalchemy2.types.Geometry(
            geometry_type="POINT",
            from_text="ST_GeomFromEWKT",
            name="geometry",
            _spatial_index_reflected=True,
        ),
        existing_nullable=True,
    )
    # ### end Alembic commands ###
