"""migration

Revision ID: 66add23d112a
Revises: d09d496c8f6e
Create Date: 2025-07-30 16:25:27.220935

"""

from collections.abc import Sequence

# revision identifiers, used by Alembic.
revision: str = "66add23d112a"
down_revision: str | None = "d09d496c8f6e"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
