"""migration

Revision ID: 7da0b1b74155
Revises: b4363c1e2f3c
Create Date: 2025-07-31 20:18:43.964462

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "7da0b1b74155"
down_revision: str | None = "b4363c1e2f3c"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "clear_cut_report_forms",
        "editor_id",
        existing_type=sa.INTEGER(),
        nullable=False,
    )
    op.drop_index(
        "ix_clear_cut_report_forms_editor_id", table_name="clear_cut_report_forms"
    )
    op.create_foreign_key(
        None, "clear_cut_report_forms", "users", ["editor_id"], ["id"]
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "clear_cut_report_forms", type_="foreignkey")
    op.create_index(
        "ix_clear_cut_report_forms_editor_id",
        "clear_cut_report_forms",
        ["editor_id"],
        unique=False,
    )
    op.alter_column(
        "clear_cut_report_forms", "editor_id", existing_type=sa.INTEGER(), nullable=True
    )
    # ### end Alembic commands ###
