"""migration

Revision ID: 8042be50cde3
Revises: 01ce59715a3d
Create Date: 2025-04-18 20:20:00.325595

"""

from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "8042be50cde3"
down_revision: Union[str, None] = "01ce59715a3d"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "rules",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("type", sa.String(), nullable=False),
        sa.Column("threshold", sa.Float(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_rules_id"), "rules", ["id"], unique=False)
    op.create_table(
        "rules_ecological_zonings",
        sa.Column("rule_id", sa.Integer(), nullable=False),
        sa.Column("ecological_zoning_id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["ecological_zoning_id"],
            ["ecological_zonings.id"],
        ),
        sa.ForeignKeyConstraint(
            ["rule_id"],
            ["rules.id"],
        ),
        sa.PrimaryKeyConstraint("rule_id", "ecological_zoning_id"),
    )
    op.drop_column("clear_cut_ecological_zoning", "area_hectare")
    op.add_column(
        "clear_cuts", sa.Column("bdf_resinous_area_ha", sa.Float(), nullable=True)
    )
    op.add_column(
        "clear_cuts", sa.Column("bdf_decidous_area_ha", sa.Float(), nullable=True)
    )
    op.add_column(
        "clear_cuts", sa.Column("bdf_mixed_area_ha", sa.Float(), nullable=True)
    )
    op.add_column(
        "clear_cuts", sa.Column("bdf_poplar_area_ha", sa.Float(), nullable=True)
    )
    op.add_column(
        "clear_cuts", sa.Column("ecological_zoning_area_ha", sa.Float(), nullable=True)
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("clear_cuts", "ecological_zoning_area_ha")
    op.drop_column("clear_cuts", "bdf_poplar_area_ha")
    op.drop_column("clear_cuts", "bdf_mixed_area_ha")
    op.drop_column("clear_cuts", "bdf_decidous_area_ha")
    op.drop_column("clear_cuts", "bdf_resinous_area_ha")
    op.add_column(
        "clear_cut_ecological_zoning",
        sa.Column(
            "area_hectare",
            sa.DOUBLE_PRECISION(precision=53),
            autoincrement=False,
            nullable=False,
        ),
    )
    op.drop_table("rules_ecological_zonings")
    op.drop_index(op.f("ix_rules_id"), table_name="rules")
    op.drop_table("rules")
    # ### end Alembic commands ###
