"""migration

Revision ID: 891e397cd11c
Revises: 996d0b13fb1c
Create Date: 2025-04-21 22:19:36.330403

"""

from typing import Sequence, Union

# revision identifiers, used by Alembic.
revision: str = "891e397cd11c"
down_revision: Union[str, None] = "996d0b13fb1c"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
