"""migration

Revision ID: 8bdf51838f72
Revises: bbbb7adf9117
Create Date: 2025-03-12 07:03:55.318858

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "8bdf51838f72"
down_revision: Union[str, None] = "bbbb7adf9117"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("departments", sa.Column("name", sa.String(), nullable=True))
    op.alter_column(
        "departments",
        "code",
        existing_type=sa.INTEGER(),
        type_=sa.String(),
        existing_nullable=True,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # A bit janky but it ensures that the next statement won't fail if there is a code
    # that is alpha in it
    op.execute(
        """
        DELETE FROM departments
        WHERE code !~ '^[0-9]+$';
        """
    )
    op.alter_column(
        "departments",
        "code",
        existing_type=sa.String(),
        type_=sa.INTEGER(),
        existing_nullable=True,
        postgresql_using="code::integer",
    )
    op.drop_column("departments", "name")
    # ### end Alembic commands ###
