"""migration

Revision ID: 8bdf51838f72
Revises: bbbb7adf9117
Create Date: 2025-03-12 07:03:55.318858

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import geoalchemy2


# revision identifiers, used by Alembic.
revision: str = '8bdf51838f72'
down_revision: Union[str, None] = 'bbbb7adf9117'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('departments', sa.Column('name', sa.String(), nullable=True))
    op.alter_column('departments', 'code',
               existing_type=sa.INTEGER(),
               type_=sa.String(),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # op.alter_column('departments', 'code',
    #            existing_type=sa.String(),
    #            type_=sa.INTEGER(),
    #            existing_nullable=True)

    # Use specific PostgreSQL command to convert column instead of autogenerated code
    op.execute('ALTER TABLE departments ALTER COLUMN code TYPE INTEGER USING code::integer')
    op.drop_column('departments', 'name')
    # ### end Alembic commands ###
