"""migration

Revision ID: 942347f79b19
Revises: ea719a350e4f
Create Date: 2025-04-21 20:37:09.701521

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "942347f79b19"
down_revision: str | None = "ea719a350e4f"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "clear_cuts_reports", sa.Column("total_area_hectare", sa.Float(), nullable=True)
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("clear_cuts_reports", "total_area_hectare")
    # ### end Alembic commands ###
