"""migration

Revision ID: 996d0b13fb1c
Revises: 942347f79b19
Create Date: 2025-04-21 20:39:01.493672

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import geoalchemy2


# revision identifiers, used by Alembic.
revision: str = '996d0b13fb1c'
down_revision: Union[str, None] = '942347f79b19'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('clear_cuts_reports', sa.Column('total_ecological_zoning_area_hectare', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('clear_cuts_reports', 'total_ecological_zoning_area_hectare')
    # ### end Alembic commands ###
