"""Add image fields to clear cut forms

Revision ID: 9ad0592d67dd
Revises: 07204d7b80f9
Create Date: 2025-07-09 02:40:56.343922

"""

from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "9ad0592d67dd"
down_revision: Union[str, None] = "07204d7b80f9"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "clear_cut_report_forms",
        sa.Column("images_clear_cut", sa.JSON(), nullable=True),
    )
    op.add_column(
        "clear_cut_report_forms",
        sa.Column("images_plantation", sa.JSON(), nullable=True),
    )
    op.add_column(
        "clear_cut_report_forms",
        sa.Column("image_worksite_sign", sa.String(), nullable=True),
    )
    op.add_column(
        "clear_cut_report_forms",
        sa.Column("images_tree_trunks", sa.JSON(), nullable=True),
    )
    op.add_column(
        "clear_cut_report_forms",
        sa.Column("images_soil_state", sa.JSON(), nullable=True),
    )
    op.add_column(
        "clear_cut_report_forms",
        sa.Column("images_access_road", sa.JSON(), nullable=True),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("clear_cut_report_forms", "images_access_road")
    op.drop_column("clear_cut_report_forms", "images_soil_state")
    op.drop_column("clear_cut_report_forms", "images_tree_trunks")
    op.drop_column("clear_cut_report_forms", "image_worksite_sign")
    op.drop_column("clear_cut_report_forms", "images_plantation")
    op.drop_column("clear_cut_report_forms", "images_clear_cut")
    # ### end Alembic commands ###
