"""migration

Revision ID: b5935c34f9bd
Revises: 9ba44a77af28
Create Date: 2025-03-20 10:00:15.629821

"""

from typing import Sequence, Union

from alembic import op
import geoalchemy2


# revision identifiers, used by Alembic.
revision: str = "b5935c34f9bd"
down_revision: Union[str, None] = "9ba44a77af28"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "clear_cuts",
        "boundary",
        existing_type=geoalchemy2.types.Geometry(
            geometry_type="POLYGON",
            from_text="ST_GeomFromEWKT",
            name="geometry",
            _spatial_index_reflected=True,
        ),
        type_=geoalchemy2.types.Geometry(
            geometry_type="MULTIPOLYGON",
            srid=4326,
            from_text="ST_GeomFromEWKT",
            name="geometry",
        ),
        existing_nullable=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "clear_cuts",
        "boundary",
        existing_type=geoalchemy2.types.Geometry(
            geometry_type="MULTIPOLYGON",
            srid=4326,
            from_text="ST_GeomFromEWKT",
            name="geometry",
        ),
        type_=geoalchemy2.types.Geometry(
            geometry_type="POLYGON",
            from_text="ST_GeomFromEWKT",
            name="geometry",
            _spatial_index_reflected=True,
        ),
        existing_nullable=False,
    )
    # ### end Alembic commands ###
