"""migration

Revision ID: d2af15e25d10
Revises: 5ccd539dde75
Create Date: 2025-07-31 20:59:13.974574

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import geoalchemy2


# revision identifiers, used by Alembic.
revision: str = 'd2af15e25d10'
down_revision: Union[str, None] = '5ccd539dde75'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('clear_cuts_reports', sa.Column('satellite_imgs', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('clear_cuts_reports', 'satellite_imgs')
    # ### end Alembic commands ###
