"""migration

Revision ID: d5d86941d29e
Revises: 342bfc046428
Create Date: 2025-03-23 14:36:09.275258

"""

from typing import Sequence, Union


# revision identifiers, used by Alembic.
revision: str = "d5d86941d29e"
down_revision: Union[str, None] = "342bfc046428"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
