"""migration

Revision ID: d88263fc04cc
Revises: 07b03ef0918b
Create Date: 2025-04-21 20:07:28.030604

"""

from typing import Sequence, Union

import geoalchemy2
import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "d88263fc04cc"
down_revision: Union[str, None] = "07b03ef0918b"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "rules_clear_cuts_reports",
        sa.Column("rule_id", sa.Integer(), nullable=False),
        sa.Column("report_id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["report_id"],
            ["clear_cuts_reports.id"],
        ),
        sa.ForeignKeyConstraint(
            ["rule_id"],
            ["rules.id"],
        ),
        sa.PrimaryKeyConstraint("rule_id", "report_id"),
    )
    op.add_column(
        "clear_cuts_reports",
        sa.Column("total_bdf_resinous_area_hectare", sa.Float(), nullable=True),
    )
    op.add_column(
        "clear_cuts_reports",
        sa.Column("total_bdf_deciduous_area_hectare", sa.Float(), nullable=True),
    )
    op.add_column(
        "clear_cuts_reports",
        sa.Column("total_bdf_mixed_area_hectare", sa.Float(), nullable=True),
    )
    op.add_column(
        "clear_cuts_reports",
        sa.Column("total_bdf_poplar_area_hectare", sa.Float(), nullable=True),
    )
    op.add_column(
        "clear_cuts_reports",
        sa.Column(
            "average_location",
            geoalchemy2.types.Geometry(
                geometry_type="POINT",
                srid=4326,
                from_text="ST_GeomFromEWKT",
                name="geometry",
            ),
            nullable=True,
        ),
    )
    op.add_column(
        "clear_cuts_reports", sa.Column("last_cut_date", sa.DateTime(), nullable=True)
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("clear_cuts_reports", "last_cut_date")
    op.drop_column("clear_cuts_reports", "average_location")
    op.drop_column("clear_cuts_reports", "total_bdf_poplar_area_hectare")
    op.drop_column("clear_cuts_reports", "total_bdf_mixed_area_hectare")
    op.drop_column("clear_cuts_reports", "total_bdf_deciduous_area_hectare")
    op.drop_column("clear_cuts_reports", "total_bdf_resinous_area_hectare")
    op.drop_table("rules_clear_cuts_reports")
    # ### end Alembic commands ###
