"""migration

Revision ID: ea719a350e4f
Revises: d88263fc04cc
Create Date: 2025-04-21 20:34:35.632240

"""

from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "ea719a350e4f"
down_revision: Union[str, None] = "d88263fc04cc"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "clear_cuts_reports", sa.Column("first_cut_date", sa.DateTime(), nullable=True)
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("clear_cuts_reports", "first_cut_date")
    # ### end Alembic commands ###
