"""migration

Revision ID: f276f1b8b4ed
Revises: 41e62d8226ee
Create Date: 2025-03-26 17:59:57.423269

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import geoalchemy2


# revision identifiers, used by Alembic.
revision: str = 'f276f1b8b4ed'
down_revision: Union[str, None] = '41e62d8226ee'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('clear_cuts', 'city_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('clear_cuts', 'user_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.drop_index('ix_clear_cuts_city_id', table_name='clear_cuts')
    op.drop_index('ix_clear_cuts_user_id', table_name='clear_cuts')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('ix_clear_cuts_user_id', 'clear_cuts', ['user_id'], unique=False)
    op.create_index('ix_clear_cuts_city_id', 'clear_cuts', ['city_id'], unique=False)
    op.alter_column('clear_cuts', 'user_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('clear_cuts', 'city_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###
