"""migration

Revision ID: f2e84934dca4
Revises: d2af15e25d10
Create Date: 2025-07-31 21:03:03.059958

"""

from collections.abc import Sequence

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "f2e84934dca4"
down_revision: str | None = "d2af15e25d10"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "clear_cuts_reports", sa.Column("statellite_images", sa.JSON(), nullable=True)
    )
    op.drop_column("clear_cuts_reports", "satellite_imgs")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "clear_cuts_reports",
        sa.Column(
            "satellite_imgs",
            postgresql.JSON(astext_type=sa.Text()),
            autoincrement=False,
            nullable=True,
        ),
    )
    op.drop_column("clear_cuts_reports", "statellite_images")
    # ### end Alembic commands ###
