/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { createFileRoute } from '@tanstack/react-router'

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as LoginImport } from './routes/login'
import { Route as AdministrationImport } from './routes/administration'
import { Route as ClearCutsImport } from './routes/_clear-cuts'
import { Route as AuthImport } from './routes/_auth'

// Create Virtual Routes

const IndexLazyImport = createFileRoute('/')()
const ClearCutsClearCutsIndexLazyImport = createFileRoute(
  '/_clear-cuts/clear-cuts/',
)()
const ClearCutsClearCutsClearCutIdLazyImport = createFileRoute(
  '/_clear-cuts/clear-cuts/$clearCutId',
)()

// Create/Update Routes

const LoginRoute = LoginImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRoute,
} as any)

const AdministrationRoute = AdministrationImport.update({
  id: '/administration',
  path: '/administration',
  getParentRoute: () => rootRoute,
} as any)

const ClearCutsRoute = ClearCutsImport.update({
  id: '/_clear-cuts',
  getParentRoute: () => rootRoute,
} as any)

const AuthRoute = AuthImport.update({
  id: '/_auth',
  getParentRoute: () => rootRoute,
} as any)

const IndexLazyRoute = IndexLazyImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRoute,
} as any).lazy(() => import('./routes/index.lazy').then((d) => d.Route))

const ClearCutsClearCutsIndexLazyRoute =
  ClearCutsClearCutsIndexLazyImport.update({
    id: '/clear-cuts/',
    path: '/clear-cuts/',
    getParentRoute: () => ClearCutsRoute,
  } as any).lazy(() =>
    import('./routes/_clear-cuts.clear-cuts.index.lazy').then((d) => d.Route),
  )

const ClearCutsClearCutsClearCutIdLazyRoute =
  ClearCutsClearCutsClearCutIdLazyImport.update({
    id: '/clear-cuts/$clearCutId',
    path: '/clear-cuts/$clearCutId',
    getParentRoute: () => ClearCutsRoute,
  } as any).lazy(() =>
    import('./routes/_clear-cuts.clear-cuts.$clearCutId.lazy').then(
      (d) => d.Route,
    ),
  )

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexLazyImport
      parentRoute: typeof rootRoute
    }
    '/_auth': {
      id: '/_auth'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof AuthImport
      parentRoute: typeof rootRoute
    }
    '/_clear-cuts': {
      id: '/_clear-cuts'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof ClearCutsImport
      parentRoute: typeof rootRoute
    }
    '/administration': {
      id: '/administration'
      path: '/administration'
      fullPath: '/administration'
      preLoaderRoute: typeof AdministrationImport
      parentRoute: typeof rootRoute
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginImport
      parentRoute: typeof rootRoute
    }
    '/_clear-cuts/clear-cuts/$clearCutId': {
      id: '/_clear-cuts/clear-cuts/$clearCutId'
      path: '/clear-cuts/$clearCutId'
      fullPath: '/clear-cuts/$clearCutId'
      preLoaderRoute: typeof ClearCutsClearCutsClearCutIdLazyImport
      parentRoute: typeof ClearCutsImport
    }
    '/_clear-cuts/clear-cuts/': {
      id: '/_clear-cuts/clear-cuts/'
      path: '/clear-cuts'
      fullPath: '/clear-cuts'
      preLoaderRoute: typeof ClearCutsClearCutsIndexLazyImport
      parentRoute: typeof ClearCutsImport
    }
  }
}

// Create and export the route tree

interface ClearCutsRouteChildren {
  ClearCutsClearCutsClearCutIdLazyRoute: typeof ClearCutsClearCutsClearCutIdLazyRoute
  ClearCutsClearCutsIndexLazyRoute: typeof ClearCutsClearCutsIndexLazyRoute
}

const ClearCutsRouteChildren: ClearCutsRouteChildren = {
  ClearCutsClearCutsClearCutIdLazyRoute: ClearCutsClearCutsClearCutIdLazyRoute,
  ClearCutsClearCutsIndexLazyRoute: ClearCutsClearCutsIndexLazyRoute,
}

const ClearCutsRouteWithChildren = ClearCutsRoute._addFileChildren(
  ClearCutsRouteChildren,
)

export interface FileRoutesByFullPath {
  '/': typeof IndexLazyRoute
  '': typeof ClearCutsRouteWithChildren
  '/administration': typeof AdministrationRoute
  '/login': typeof LoginRoute
  '/clear-cuts/$clearCutId': typeof ClearCutsClearCutsClearCutIdLazyRoute
  '/clear-cuts': typeof ClearCutsClearCutsIndexLazyRoute
}

export interface FileRoutesByTo {
  '/': typeof IndexLazyRoute
  '': typeof ClearCutsRouteWithChildren
  '/administration': typeof AdministrationRoute
  '/login': typeof LoginRoute
  '/clear-cuts/$clearCutId': typeof ClearCutsClearCutsClearCutIdLazyRoute
  '/clear-cuts': typeof ClearCutsClearCutsIndexLazyRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/': typeof IndexLazyRoute
  '/_auth': typeof AuthRoute
  '/_clear-cuts': typeof ClearCutsRouteWithChildren
  '/administration': typeof AdministrationRoute
  '/login': typeof LoginRoute
  '/_clear-cuts/clear-cuts/$clearCutId': typeof ClearCutsClearCutsClearCutIdLazyRoute
  '/_clear-cuts/clear-cuts/': typeof ClearCutsClearCutsIndexLazyRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | ''
    | '/administration'
    | '/login'
    | '/clear-cuts/$clearCutId'
    | '/clear-cuts'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | ''
    | '/administration'
    | '/login'
    | '/clear-cuts/$clearCutId'
    | '/clear-cuts'
  id:
    | '__root__'
    | '/'
    | '/_auth'
    | '/_clear-cuts'
    | '/administration'
    | '/login'
    | '/_clear-cuts/clear-cuts/$clearCutId'
    | '/_clear-cuts/clear-cuts/'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  IndexLazyRoute: typeof IndexLazyRoute
  AuthRoute: typeof AuthRoute
  ClearCutsRoute: typeof ClearCutsRouteWithChildren
  AdministrationRoute: typeof AdministrationRoute
  LoginRoute: typeof LoginRoute
}

const rootRouteChildren: RootRouteChildren = {
  IndexLazyRoute: IndexLazyRoute,
  AuthRoute: AuthRoute,
  ClearCutsRoute: ClearCutsRouteWithChildren,
  AdministrationRoute: AdministrationRoute,
  LoginRoute: LoginRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/_auth",
        "/_clear-cuts",
        "/administration",
        "/login"
      ]
    },
    "/": {
      "filePath": "index.lazy.tsx"
    },
    "/_auth": {
      "filePath": "_auth.tsx"
    },
    "/_clear-cuts": {
      "filePath": "_clear-cuts.tsx",
      "children": [
        "/_clear-cuts/clear-cuts/$clearCutId",
        "/_clear-cuts/clear-cuts/"
      ]
    },
    "/administration": {
      "filePath": "administration.tsx"
    },
    "/login": {
      "filePath": "login.tsx"
    },
    "/_clear-cuts/clear-cuts/$clearCutId": {
      "filePath": "_clear-cuts.clear-cuts.$clearCutId.lazy.tsx",
      "parent": "/_clear-cuts"
    },
    "/_clear-cuts/clear-cuts/": {
      "filePath": "_clear-cuts.clear-cuts.index.lazy.tsx",
      "parent": "/_clear-cuts"
    }
  }
}
ROUTE_MANIFEST_END */
