name: Backend Database actions 
description: Enable database actions based on Makefile commands

on:
  workflow_dispatch:
    inputs:
      database-action:
        required: true
        options:
          - setup-database
          - reset-database
        type: choice
        description: 'Seed the database with test data'

concurrency:
  group: ci-${{ github.ref }}
  cancel-in-progress: true

jobs:
  seed-database:
    env:
        DATABASE_URL: ${{secrets.DATABASE_URL}}
        ENVIRONMENT: development
        
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.13"]
    steps:
        - uses: actions/checkout@v4
        - name: Set up Python ${{ matrix.python-version }}
          uses: actions/setup-python@v5
          with:
            python-version: ${{ matrix.python-version }}
        - name : Install Poetry
          run: |
            python -m pip install --upgrade pip
            pip install poetry
        - name: Run action ${{inputs.database-action}}
          working-directory: backend
          run: make install-dev-dependencies && ${{inputs.database-action == 'setup-database' &&  'make upgrade-db && make seed-db' ||  'make reset-db'}} 