# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Frontend CI

on:
  workflow_dispatch:
  push:
    branches: ["main"]
    paths:
      - "frontend/**"
  pull_request:
    branches: ["main"]
    paths:
      - "frontend/**"

env:
  PLAYWRIGHT_BROWSERS_PATH: ${{ github.workspace }}/.cache/ms-playwright
jobs:
  build-test:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: frontend

    steps:
      - uses: actions/checkout@v4

      - name: Install pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 10
          run_install: false

      - name: Install Node.js v22.11.0
        uses: actions/setup-node@v4
        with:
          node-version: 22.11.0

      - name: Install dependencies
        run: pnpm install

      - name: Install playwright
        run: pnpm install:playwright
        
      - name: Build project
        run: pnpm run build

      - name: Run tests
        run: pnpm test

  deploy:
    needs: build-test
    uses: "./.github/workflows/deploy.yml"
    secrets: inherit
    with:
      app-id: app_ab2f14d8-10a9-454d-9a7d-92ab22a54110
      app-name: "frontend"
