[tool.poetry]
name = "bcr-data-pipeline"
version = "0.1.0"
description = "ETL subproject to ingest datasources, process and load clear cuts data model into the main DB"
authors = ["DataForGood"]
license = "MIT"
readme = "README.md"
package-mode = false

[tool.poetry.dependencies]
python = "^3.13"
requests = "^2.32.3"
geopandas = "^1.0.1"
psutil = "^7.0.0"
